apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: github-project
  name: github-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: github-project
    spec:
      containers:
      - image: yeswanthk/devsec-1
        name: github-project
        ports:
        - containerPort: 8080
        resources: {}
status: {}
